# Generated by Django 4.1.7 on 2023-04-06 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_accrec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accrec',
            name='topic_name',
        ),
        migrations.AlterField(
            model_name='accrec',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.webpage'),
        ),
    ]
